Update simulate

diff --git a/production/simulate b/production/simulate
--- a/production/simulate
+++ b/production/simulate
@@ -380,14 +380,14 @@ generate_protein_topology() {
     # Check auto_check function
     if [[ $(auto_check) == true ]]; then
         remove_hetatm
-        gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$force_field" -water "$water_model" -ignh >/dev/null 2>&1
+        gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$ff" -water "$wm" -ignh >/dev/null 2>&1
         local exit_status=$?
         if [[ $exit_status -ne 0 ]]; then
             echo -e "${LIGHT_RED}Error: Failed to generate protein topology. Attempting to fix PDB file.${NC}"
-            pdb_fixer 
+            pdb_fixer || { echo -e "${LIGHT_RED}Error: PDB fixer failed. Exiting.${NC}"; exit 1; }
             
             # Retry GROMACS pdb2gmx after fixing
-            gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$force_field" -water "$water_model" -ignh >/dev/null 2>&1
+            gmx pdb2gmx -f "$project_dir/protein.pdb" -o "$project_dir/protein.gro" -ff "$ff" -water "$wm" -ignh >/dev/null 2>&1
             exit_status=$?
             if [[ $exit_status -ne 0 ]]; then
                 echo -e "${LIGHT_RED}Error: Topology generation failed after fixing.${NC}"
@@ -443,9 +443,9 @@ generate_protein_topology() {
 # Function to define box and solvate the system
 define_box_and_solvate() {
     if [[ $(auto_check) == true ]]; then
-        gmx editconf -f $project_dir/protein.gro -o $project_dir/newbox.gro -c -d 1.0 -bt $box_type >/dev/null 2>&1 &
+        gmx editconf -f $project_dir/protein.gro -o $project_dir/newbox.gro -c -d 1.0 -bt $bt >/dev/null 2>&1 &
         box_loader
-        gmx solvate -cp $project_dir/newbox.gro -cs $solvate_model.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
+        gmx solvate -cp $project_dir/newbox.gro -cs $sol_mod.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
         solvate_loader
     else
     echo
