Update complex_sim

diff --git a/production/core/complex/complex_sim b/production/core/complex/complex_sim
--- a/production/core/complex/complex_sim
+++ b/production/core/complex/complex_sim
@@ -99,6 +99,45 @@ equilibration_loader() {
     fi
 }
 
+#Solvate model loader
+solvate_loader() {
+    show_spinner $! "Solvating the system"
+    wait $!
+    if [ $? -ne 0 ]; then
+        echo -e "${LIGHT_RED}Error: Failed to solvate the system. See log file for more info.${NC}"
+        exit 1
+    else
+        echo -e ${LIGHT_GREEN}"System solvated successfully!"${NC}
+        sleep 1.0
+    fi
+}
+
+#ion tpr loader
+ion_tpr_loader() {
+    show_spinner $! "Adding ions to the system"
+    wait $!
+    if [ $? -ne 0 ]; then
+        echo -e "${LIGHT_RED}Error: Failed to generate ions.tpr. See log file for more info.${NC}"
+        exit 1
+    else
+        echo -e ${LIGHT_GREEN}"Ions.tpr generated successfully"${NC}
+        sleep 1.0
+    fi
+}
+
+#Ion addition loader
+ion_add_loader() {
+    show_spinner $! "Adding ions to the system"
+    wait $!
+    if [ $? -ne 0 ]; then
+        echo -e "${LIGHT_RED}Error: Failed to add ions. See log file for more info.${NC}"
+        exit 1
+    else
+        echo -e ${LIGHT_GREEN}"Ions added successfully"${NC}
+        sleep 1.0
+    fi
+}
+
 #check internet connection
 check_internet() {
     if ping -c 1 -W 1 8.8.8.8 &>/dev/null; then
@@ -417,6 +456,7 @@ prepare_ligand_topology() {
                 if [ -f "$perl_sort_file" ]; then
                     check_file_exists "lig_fix.mol2" || return
                     perl sort_mol2_bonds.pl lig.mol2 lig_fix.mol2
+                    sed -i 's/lig\.pdb/LIG/g' lig_fix.mol2
                 else
                     echo "$perl_sort_file does not exist."
                     exit 1
@@ -528,15 +568,83 @@ prepare_ligand_topology() {
 
 # Function to define box and solvate the system
 define_box_and_solvate() {
-    echo "Defining box and solvating system..."
-    if [ ! -f "complex.gro" ]; then
-        echo "complex.gro does not exist."
-        exit 1
-    fi
-    check_file_exists "newbox.gro" || return
-    gmx editconf -f complex.gro -o newbox.gro -bt dodecahedron -d 1.0 || { echo "Error: Failed to define the box."; exit 1; }
-    check_file_exists "solv.gro" || return
-    gmx solvate -cp newbox.gro -cs spc216.gro -p topol.top -o solv.gro || { echo "Error: Failed to solvate the system."; exit 1; }
+echo
+echo "Defining box and solvating system..."
+echo
+if [ ! -f "$project_dir/protein.gro" ]; then
+    echo -e ${LIGHT_RED} "protein.gro does not exist.${NC}"
+    sleep 2.0
+    exit 1
+fi
+check_file_exists "$project_dir/solv.gro" || return
+echo -e ${YELLOW}
+read -p "Do you want to continue with the default box type and solvation model (Cubic/SPC)? (y/n): " select_solvate_box
+echo -e ${NC}
+if [ $select_solvate_box == "y" ]; then
+    gmx editconf -f $project_dir/protein.gro -o $project_dir/newbox.gro -c -d 1.0 -bt cubic >/dev/null 2>&1 &
+    box_loader
+    echo
+    gmx solvate -cp $project_dir/newbox.gro -cs spc216.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
+    solvate_loader
+else
+    echo -e ${YELLOW}"Select box type from the following${NC}"
+    echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} Cubic"
+    #echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Octahedral"
+    echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} Dodecahedron"
+    echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} Triclinic"
+    choice=$(prompt_user "Enter your choice [1-3]: ")
+    echo -e ${NC}
+
+    case $choice in
+    1)
+        gmx editconf -f $project_dir/protein.gro -o $project_dir/newbox.gro -c -d 1.0 -bt cubic >/dev/null 2>&1 &
+        box_loader
+        ;;
+    #2) gmx editconf -f protein.gro -o newbox.gro -c -d 1.0 -bt octahedral || { echo -e ${LIGHT_RED} "Error: Failed to define the box.${NC}"
+    #sleep 2.0; exit 1; } ;;
+    2)
+        gmx editconf -f $project_dir/protein.gro -o $project_dir/newbox.gro -c -d 1.0 -bt dodecahedron >/dev/null 2>&1 &
+        box_loader
+        ;;
+    3)
+        gmx editconf -f $project_dir/protein.gro -o $project_dir/newbox.gro -c -d 1.0 -bt triclinic >/dev/null 2>&1 &
+        box_loader
+        ;;
+    *)
+        echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
+        sleep 1.0
+        ;;
+    esac
+    echo
+    echo -e ${YELLOW}"Select solvation model from the following${NC}"
+    echo -e "${LIGHT_PURPLE}[${NC}01${LIGHT_PURPLE}]${NC} SPC"
+    #echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} SPC/E"
+    echo -e "${LIGHT_PURPLE}[${NC}02${LIGHT_PURPLE}]${NC} TIP3P"
+    echo -e "${LIGHT_PURPLE}[${NC}03${LIGHT_PURPLE}]${NC} TIP4P"
+    choice=$(prompt_user "Enter your choice [1-3]: ")
+    echo -e ${NC}
+
+    case $choice in
+    1)
+        gmx solvate -cp $project_dir/newbox.gro -cs spc216.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
+        solvate_loader
+        ;;
+    #2) gmx solvate -cp newbox.gro -cs spce216.gro -p topol.top -o solv.gro || { echo -e ${LIGHT_RED} "Error: Failed to solvate the system.${NC}"
+    #sleep 2.0; exit 1; } ;;
+    2)
+        gmx solvate -cp $project_dir/newbox.gro -cs tip3p.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
+        solvate_loader
+        ;;
+    3)
+        gmx solvate -cp $project_dir/newbox.gro -cs tip4p.gro -p $project_dir/topol.top -o $project_dir/solv.gro >/dev/null 2>&1 &
+        solvate_loader
+        ;;
+    *)
+        echo -e "${LIGHT_RED}Invalid option! Please select between 1 and 3.${NC}"
+        sleep 1.0
+        ;;
+    esac
+fi
 }
 
 # Function to add ions
