update protein sim and added extract frames function

diff --git a/production/core/protein/protein_sim b/production/core/protein/protein_sim
--- a/production/core/protein/protein_sim
+++ b/production/core/protein/protein_sim
@@ -1202,111 +1202,157 @@ production_md() {
             echo "Elapsed time: $elapsed seconds"
             sleep 2.0
         fi
-        echo
-        echo -e "Processing files..."
-        echo
-        #Recentering and Rewrapping Coordinates...
-        if [ ! -f "$project_dir/md.xtc" ]; then
-            echo -e ${LIGHT_RED} "md.xtc does not exist.${NC}"
-            exit 1
-        fi
-        check_file_exists "$project_dir/md_noPBC.xtc" || return
-        printf "1 0\n" | gmx trjconv -s $project_dir/md.tpr -f $project_dir/md.xtc -o $project_dir/md_noPBC.xtc -pbc mol -center >/dev/null 2>&1 || exit 1
-
-        #Finding RMSD...
-        if [ ! -f "$project_dir/md_noPBC.xtc" ]; then
-            echo -e ${LIGHT_RED} "md_noPBC.xtc does not exist.${NC}"
-            exit 1
-        fi
-        check_file_exists "$project_dir/rmsd.xvg" || return
-        printf "4 4\n" | gmx rms -s $project_dir/md.tpr -f $project_dir/md_noPBC.xtc -o $project_dir/rmsd.xvg -tu ns >/dev/null 2>&1 || exit 1
-        wait
-        manual_run
     fi
-
-    simulation_time=$md_time_ps
-
-    # Define the interval (100 ps)
-    interval=100
-
-    # Initialize the start time
-    start_time=0
-
-    # Loop through the time steps and extract frames
-    while [ $start_time -le $simulation_time ]; do
-        # Here you can call the command to extract the frame, e.g.:
-        printf "1\n" | gmx trjconv -s md.tpr -f md.xtc -o $frames_dir/frame_${start_time}.pdb -b $start_time -e $start_time
-        ((start_time+=interval))
-    done
-
-    # If the last frame isn't exactly a multiple of the interval, add it
-    if [ $(($simulation_time % $interval)) -ne 0 ]; then
-        # Similarly, you can call the command to extract the last frame
-        printf "1\n" | gmx trjconv -s md.tpr -f md.xtc -o $frames_dir/frame_${simulation_time}.pdb -b $simulation_time -e $simulation_time
-    fi
-    #Finding Radius of Gyration...
-    # if [ ! -f "$project_dir/md_noPBC.xtc" ]; then
-    #     echo -e ${LIGHT_RED} "md_noPBC.xtc does not exist.${NC}"
-    #     exit 1
-    # fi
-    # check_file_exists "$project_dir/gyrate.xvg" || return
-    # printf "1\n" | gmx gyrate -s $project_dir/md.tpr -f $project_dir/md_noPBC.xtc -o $project_dir/gyrate.xvg >/dev/null 2>&1 || exit 1
-
-    # #Analyzing Hbonds...
-    # if [ ! -f "$project_dir/md_noPBC.xtc" ]; then
-    #     echo -e ${LIGHT_RED} "md_noPBC.xtc does not exist.${NC}"
-    #     exit 1
-    # fi
-    # check_file_exists "$project_dir/hbnum.xvg" || return
-    # check_file_exists "$project_dir/hbdist.xvg" || return
-    # printf "1 11\n" |  gmx hbond -f $project_dir/md_noPBC.xtc -s $project_dir/md.tpr -num -dist > /dev/null 2>&1 || exit 1
-
-    # #Analyzing RMSF...
-    # if [ ! -f "$project_dir/md_noPBC.xtc" ]; then
-    #     echo -e ${LIGHT_RED} "md_noPBC.xtc does not exist.${NC}"
-    #     exit 1
-    # fi
-    # check_file_exists "$project_dir/rmsf.xvg" || return
-    # printf "1\n" | gmx rmsf -f $project_dir/md_noPBC.xtc -s $project_dir/md.tpr -o $project_dir/rmsf.xvg >/dev/null 2>&1 || exit 1
-
-    # #Analyzing Temp...
-    # if [ ! -f "$project_dir/nvt.edr" ]; then
-    #     echo -e ${LIGHT_RED} "nvt.edr does not exist.${NC}"
-    #     exit 1
-    # fi
-    # check_file_exists "$project_dir/temp.xvg" || return
-    # printf "17\n" | gmx energy -f $project_dir/nvt.edr -o $project_dir/temp.xvg >/dev/null 2>&1 || exit 1
-
-    # #Analyzing Pressure...
-    # if [ ! -f "$project_dir/npt.edr" ]; then
-    #     echo -e ${LIGHT_RED} "npt.edr does not exist.${NC}"
-    #     exit 1
-    # fi
-    # check_file_exists "$project_dir/pressure.xvg" || return
-    # printf "19\n" | gmx energy -f $project_dir/npt.edr -o $project_dir/pressure.xvg >/dev/null 2>&1 || exit 1
-
-    # 6)
-    #     echo
-    #     echo "Calculating Potential Energy..."
-    #     echo
-    #     if [ ! -f "$project_dir/em.edr" ]; then
-    #         echo -e ${LIGHT_RED} "em.edr does not exist.${NC}"
-    #         exit 1
-    #     fi
-    #     check_file_exists "$project_dir/potential.xvg" || return
-    #     gmx energy -f $project_dir/em.edr -o $project_dir/potential.xvg #generate temperature.xvg file
-    #     ;;
-    # Wait for background processes to finish
     wait
 }
 
-avg_stddev(){
-    local xvg_file="$1" 
+result_analyze(){
+    #Recentering and Rewrapping Coordinates...
+    if [ ! -f "md.xtc" ]; then
+        exit 1
+    fi
+    printf "1 0\n" | gmx trjconv -s md.tpr -f md.xtc -o md_noPBC.xtc -pbc mol -center || exit 1
+
+    #Finding RMSD...
+    if [ ! -f "md_noPBC.xtc" ]; then
+        exit 1
+    fi
+    printf "4 4\n" | gmx rms -s md.tpr -f md_noPBC.xtc -o rmsd.xvg -tu ns || exit 1
+
+    #Extract frames
+    # Ensure sim_time is set
+    if [ -z "$sim_time" ]; then
+        echo "Error: sim_time is not set."
+        exit 1
+    fi
+
+    # Convert sim_time from ns to ps and ensure it's an integer
+    simulation_time=$(echo "$sim_time * 1000" | bc | awk '{printf "%.0f", $1}')
+
+    if [ -z "$sim_frames" ]; then
+        if [ "$simulation_time" -ge 100 ]; then
+            # Determine interval based on sim_time
+            if [ "$simulation_time" -gt 100000 ]; then
+                interval=50000  # 50 ns
+            elif [ "$simulation_time" -gt 10000 ]; then
+                interval=5000   # 5 ns
+            elif [ "$simulation_time" -gt 1000 ]; then
+                interval=500    # 500 ps
+            else
+                interval=100    # 100 ps
+            fi
+
+            # Ensure frames directory exists
+            frames_dir="frames"
+            mkdir -p "$frames_dir"
+
+            # Initialize the start time
+            start_time=0
+
+            # Loop through the time steps and extract frames
+            while [ $start_time -le $simulation_time ]; do
+                # Here you can call the command to extract the frame, e.g.:
+                printf "1\n" | gmx trjconv -s md.tpr -f md.xtc -o $frames_dir/frame_${start_time}.pdb -b $start_time -e $start_time
+                ((start_time+=interval))
+            done
+
+            # If the last frame isn't exactly a multiple of the interval, add it
+            if [ $(($simulation_time % $interval)) -ne 0 ]; then
+                # Similarly, you can call the command to extract the last frame
+                printf "1\n" | gmx trjconv -s md.tpr -f md.xtc -o $frames_dir/frame_${simulation_time}.pdb -b $simulation_time -e $simulation_time
+            fi
+        else
+            sleep 1.0
+        fi
+    else
+        # Custom frame extraction based on user-defined frame count
+        interval=$(echo "$simulation_time / $sim_frames" | bc)
+        if [ "$interval" -lt 1 ]; then
+            interval=1
+        fi
+        # Ensure frames directory exists
+        frames_dir="frames"
+        mkdir -p "$frames_dir"
+
+        # Initialize the start time
+        start_time=0
+
+        # Loop through the time steps and extract frames
+        while [ $start_time -le $simulation_time ]; do
+            # Here you can call the command to extract the frame, e.g.:
+            printf "1\n" | gmx trjconv -s md.tpr -f md.xtc -o $frames_dir/frame_${start_time}.pdb -b $start_time -e $start_time
+            ((start_time+=interval))
+        done
+
+        # If the last frame isn't exactly a multiple of the interval, add it
+        if [ $(($simulation_time % $interval)) -ne 0 ]; then
+            # Similarly, you can call the command to extract the last frame
+            printf "1\n" | gmx trjconv -s md.tpr -f md.xtc -o $frames_dir/frame_${simulation_time}.pdb -b $simulation_time -e $simulation_time
+        fi
+    fi
+}
+
+#Finding Radius of Gyration...
+# if [ ! -f "$project_dir/md_noPBC.xtc" ]; then
+#     echo -e ${LIGHT_RED} "md_noPBC.xtc does not exist.${NC}"
+#     exit 1
+# fi
+# check_file_exists "$project_dir/gyrate.xvg" || return
+# printf "1\n" | gmx gyrate -s $project_dir/md.tpr -f $project_dir/md_noPBC.xtc -o $project_dir/gyrate.xvg >/dev/null 2>&1 || exit 1
+
+# #Analyzing Hbonds...
+# if [ ! -f "$project_dir/md_noPBC.xtc" ]; then
+#     echo -e ${LIGHT_RED} "md_noPBC.xtc does not exist.${NC}"
+#     exit 1
+# fi
+# check_file_exists "$project_dir/hbnum.xvg" || return
+# check_file_exists "$project_dir/hbdist.xvg" || return
+# printf "1 11\n" |  gmx hbond -f $project_dir/md_noPBC.xtc -s $project_dir/md.tpr -num -dist > /dev/null 2>&1 || exit 1
+
+# #Analyzing RMSF...
+# if [ ! -f "$project_dir/md_noPBC.xtc" ]; then
+#     echo -e ${LIGHT_RED} "md_noPBC.xtc does not exist.${NC}"
+#     exit 1
+# fi
+# check_file_exists "$project_dir/rmsf.xvg" || return
+# printf "1\n" | gmx rmsf -f $project_dir/md_noPBC.xtc -s $project_dir/md.tpr -o $project_dir/rmsf.xvg >/dev/null 2>&1 || exit 1
+
+# #Analyzing Temp...
+# if [ ! -f "$project_dir/nvt.edr" ]; then
+#     echo -e ${LIGHT_RED} "nvt.edr does not exist.${NC}"
+#     exit 1
+# fi
+# check_file_exists "$project_dir/temp.xvg" || return
+# printf "17\n" | gmx energy -f $project_dir/nvt.edr -o $project_dir/temp.xvg >/dev/null 2>&1 || exit 1
+
+# #Analyzing Pressure...
+# if [ ! -f "$project_dir/npt.edr" ]; then
+#     echo -e ${LIGHT_RED} "npt.edr does not exist.${NC}"
+#     exit 1
+# fi
+# check_file_exists "$project_dir/pressure.xvg" || return
+# printf "19\n" | gmx energy -f $project_dir/npt.edr -o $project_dir/pressure.xvg >/dev/null 2>&1 || exit 1
+
+# 6)
+#     echo
+#     echo "Calculating Potential Energy..."
+#     echo
+#     if [ ! -f "$project_dir/em.edr" ]; then
+#         echo -e ${LIGHT_RED} "em.edr does not exist.${NC}"
+#         exit 1
+#     fi
+#     check_file_exists "$project_dir/potential.xvg" || return
+#     gmx energy -f $project_dir/em.edr -o $project_dir/potential.xvg #generate temperature.xvg file
+#     ;;
+# Wait for background processes to finish
+
+avg_stddev() {
+    local xvg_file="$1"
     local unit="$2"
     # Define local colors using tput
-    local YELLOW=$(tput setaf 3)  # Set yellow color
-    local CYAN=$(tput setaf 6)    # Set cyan color
-    local NC=$(tput sgr0)         # Reset color to default
+    local YELLOW=$(tput setaf 3) # Set yellow color
+    local CYAN=$(tput setaf 6)   # Set cyan color
+    local NC=$(tput sgr0)        # Reset color to default
 
     # Process the file with AWK
     awk -v YELLOW="$YELLOW" -v CYAN="$CYAN" -v NC="$NC" -v unit="$unit" '
@@ -1758,38 +1804,46 @@ EOF
 
     # Step 1: Download protein
     download_protein >/dev/null 2>&1 &
-    auto_task_spinner $! "Step 1 of 7: Downloading protein structure"
+    auto_task_spinner $! "Step 1 of 8: Downloading protein structure"
 
     # Step 2: Generate protein topology
     generate_protein_topology
 
     # Step 3: Define box and solvate the system
     define_box_and_solvate >/dev/null 2>&1 &
-    auto_task_spinner $! "Step 3 0f 7: Define Box and Solvate the System"
+    auto_task_spinner $! "Step 3 0f 8: Define Box and Solvate the System"
 
     # Step 4: Add ions to system
     add_ions >/dev/null 2>&1 &
-    auto_task_spinner $! "Step 4 0f 7: Add ions to system"
+    auto_task_spinner $! "Step 4 0f 8: Add ions to system"
 
     # Step 5: Energy minimization
     energy_minimization >/dev/null 2>&1 &
-    auto_task_spinner $! "Step 5 0f 7: Minimize energy"
+    auto_task_spinner $! "Step 5 0f 8: Minimize energy"
 
     # Step 6: Equilibrate system
     equilibrium >/dev/null 2>&1 &
-    auto_task_spinner $! "Step 6 0f 7: Equilibrate system"
+    auto_task_spinner $! "Step 6 0f 8: Equilibrate system"
 
     # Step 7: Run MD Simulation
     start_time=$(date +%s)
     production_md >/dev/null 2>&1 &
-    auto_task_spinner $! "Step 7 0f 7: Run MD Simulation"
+    auto_task_spinner $! "Step 7 0f 8: Run MD Simulation"
 
     # Calculate total time taken for the simulation
     end_time=$(date +%s)
     elapsed=$((end_time - start_time))
+
+    # Convert and display elapsed time in HH:MM:SS format
+    formatted_time=$(date -u -d @"$elapsed" +%H:%M:%S)
+
+    # Step 8: Analyze results
+    result_analyze >/dev/null 2>&1 &
+    auto_task_spinner $! "Step 8 of 8: Analyzing Results"
+
     echo
     echo -e "${LIGHT_CYAN}Simulation completed on $run_mode.${NC}"
-    echo "Elapsed time: $elapsed seconds"
+    echo "Elapsed time: $formatted_time"
     echo
     sleep 1.0
     # local target_file="$project_dir/${pdb_id}.pdb"
